FROM centos:7
MAINTAINER gaurav

RUN yum -y update \
    && yum -y install https://mirror.webtatic.com/yum/el7/webtatic-release.rpm && yum -y update \
    && yum -y install httpd

# Set locales
RUN localedef -i en_US -f UTF-8 en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN rm -f /var/run/apache2/apache2.pid
COPY ./docker-config/vhosts/httpd.conf /etc/httpd/conf/httpd.conf
WORKDIR /var/www/html

EXPOSE 80
ENTRYPOINT ["/usr/sbin/httpd"]
CMD ["-DFOREGROUND"]